# Generated by Django 3.1.4 on 2020-12-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email ID')),
                ('role', models.CharField(choices=[('ADM', 'Admin'), ('REG', 'Regular')], default='REG', max_length=3)),
            ],
            options={
                'db_table': 'team_member',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
